### ISSUE TITLE
IDE Fatal Errors - Java Stack trace

### ISSUE THREAD

**Issue by ye** [42Crunch/intellij-openapi-editor#19]
Getting a Java stack trace today:

```
java.lang.Throwable: Can't remove document listener (com.xliic.openapi.listeners.BundleDocumentListener@66d9b0f5). Registered listeners: [com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1@73da1d1d, 0, 0, Multicaster, Multicaster, com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$1@5a7d1c1e]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.editor.impl.DocumentImpl.removeDocumentListener(DocumentImpl.java:1003)
	at com.xliic.openapi.services.BundleService.lambda$removeListeners$8(BundleService.java:323)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at com.xliic.openapi.services.BundleService.removeListeners(BundleService.java:319)
	at com.xliic.openapi.services.BundleService.remove(BundleService.java:260)
	at com.xliic.openapi.services.BundleService.beforeFileClosed(BundleService.java:153)
	at com.xliic.openapi.async.AsyncService.safeRun(AsyncService.java:55)
	at com.xliic.openapi.async.AsyncService.run(AsyncService.java:32)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

<img width="1394" alt="Screen Shot 2022-04-14 at 3 02 22 PM" src="https://user-images.githubusercontent.com/133924/163459873-82b5c5dd-c59b-485e-b484-6097543306b9.png">

**Comment by ak1394** [comment]
Thanks for reporting! Will update the issue once we have a fix.
