### ISSUE TITLE
Exception on PhpStorm 2022.3 Beta

### ISSUE THREAD

**Issue by matiux** [42Crunch/intellij-openapi-editor#26]
PhpStorm 2022.3 Beta
Build #PS-223.7571.15, built on November 10, 2022
Runtime version: 17.0.5+1-b653.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.0.8-arch1-1
Registry:
    editor.focus.mode.color.light=415967
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    net.sjrx.intellij.plugins.systemdunitfiles (0.3.10)
    Batch Scripts Support (1.0.13)
    org.ermadan.kafkalytic (0.10.5)
    com.crunch42.openapi (1.41)
    org.jetbrains.settingsRepository (223.7571.17)
    com.intellij.ideolog (203.0.30.0)
    com.godwin.json.parser (1.4.1)
    Statistic (4.2.6)
    String Manipulation (9.6.1)
    izhangzhihao.rainbow.brackets (2022.3.4)
    pro.bashsupport (3.0.1.223)
    com.chrisrm.idea.MaterialThemeUI (8.0.1)
    ru.adelf.idea.dotenv (2022.3)
    de.espend.idea.php.annotation (8.2.3)
    fr.adrienbrault.idea.symfony2plugin (2022.1.236)
    org.sonarlint.idea (7.2.0.56810)

Current Desktop: KDE

java.lang.NoSuchMethodError: 'void org.snakeyaml.engine.v2.serializer.Serializer.open()'
	at com.xliic.openapi.parser.ast.node.Node.dump(Node.java:231)
	at com.xliic.openapi.quickfix.QuickFix.getInstance(QuickFix.java:60)
	at com.xliic.openapi.services.QuickFixService.process(QuickFixService.java:159)
	at com.xliic.openapi.services.QuickFixService.loadJsonConfig(QuickFixService.java:221)
	at com.xliic.openapi.services.QuickFixService.load(QuickFixService.java:59)
	at com.xliic.openapi.OpenAPIStartupActivity.runActivity(OpenAPIStartupActivity.java:45)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:340)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:279)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:278)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda-0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:142)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:278)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:184)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by ak1394** [comment]
@matiux Thanks for reporting, we should fix it in the next release of the plugin!

**Comment by TheChrisPratt** [comment]
This is also showing up during the startup of 22.3 GA (#IU-223.7571.182) version of IntelliJ IDEA as well

**Comment by ak1394** [comment]
Thanks for reporting, we're working on the update, and planning to release it in the next few days.

**Comment by ak1394** [comment]
This issue has been resolved in 1.46 of the extension.
