### ISSUE TITLE
Exception thrown during autocomplete handling

### ISSUE THREAD

**Issue by equalspeterd** [42Crunch/intellij-openapi-editor#6]
While editing an openAPI 3.0.1 document (with many external `$ref` pointers, if that matters), I see this exception occur often:

```
java.lang.NullPointerException
	at com.crunch42.openapi.editor.CompletionHelper.updateResultSet(CompletionHelper.java:43)
	at com.crunch42.openapi.editor.OpenAPIYamlCompletionContributor$1.addCompletions(OpenAPIYamlCompletionContributor.java:17)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:34)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:77)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:89)
...
```

I have OpenAPI Editor v 1.15, running in IntelliJ 2021.1.1

**Comment by ak1394** [comment]
Thanks a lot for the info, we're looking into it.

**Comment by ak1394** [comment]
This issue should be resolved in the recent versions of the plugin.
