### ISSUE TITLE
Exception thrown when opening projects

### ISSUE THREAD

**Issue by EdwardSalter** [42Crunch/intellij-openapi-editor#8]
When opening any project (with or without an OpenAPI definition file), I get the following exception:

> java.lang.NullPointerException
	at com.crunch42.openapi.services.QuickFixService.process(QuickFixService.java:141)
	at com.crunch42.openapi.services.QuickFixService.load(QuickFixService.java:63)
	at com.crunch42.openapi.OpenAPIStartupActivity.runActivity(OpenAPIStartupActivity.java:18)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:335)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:309)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$4(StartupManagerImpl.java:235)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:303)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:156)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:229)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$projectOpened$1(StartupManagerImpl.java:160)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

This is with Webstorm 2021.1 and OpenAPI plugin 1.15.

**Comment by ak1394** [comment]
Thanks for the report! We're looking at it.

**Comment by ak1394** [comment]
Could you update to the latest version of the plugin (1.18) and re-try?

**Comment by EdwardSalter** [comment]
For some reason Windows has decided to stop running certain programs when it starts and so Jetbrains Toolbox has not been started for some time on my machine.
By running that and upgrading WebStorm to the latest version (2021.1.2), version 1.18 of the OpenAPI plugin became available.
After upgrading to that version as well, this issue does indeed seem to have been resolved.

Apologies for wasting your time.
